### ISSUE TITLE
Chapter 4, bech32.js - Clarify parameter name

### ISSUE THREAD

**Issue by satsie** [saving-satoshi/challenges#9]
In chapter 4, challenge 2, players are expected to look through [bech32.js](https://github.com/saving-satoshi/challenges/blob/master/chapter4/javascript/lib/bech32.js) (or the python counterpart), and identify a method that will turn the (double) hash of their compressed public key into an address. They are looking for something that creates the witness program (by appending the witness version to the public key hash), computes a checksum of the witness program, and appends it the checksum, as well as the human readable prefix to the hash.

They want the `encode()` function ([link](https://github.com/saving-satoshi/challenges/blob/c7da937ea1083289273d3729e80e26d4415105f1/chapter4/javascript/lib/bech32.js#L184C1-L194C2)):

```
exports.encode = (hrp, version, program) => {
  var enc = encodings.BECH32;
  if (version > 0) {
    enc = encodings.BECH32M;
  }
  var ret = exports.bech32_encode(hrp, [version].concat(exports.convertbits(program, 8, 5, true)), enc);
  if (exports.decode(hrp, ret) === null) {
    return null;
  }
  return ret;
}
```

Can I change the `hrp` param to `humanReadablePrefix`, or leave a code comment? I literally just figured out what it stood for right now, in the middle of filing this issue, actually in the middle of writing that last sentence. I was so stumped by it that I started poking around more and found it being used, as well as the answer to the challenge in `answer.js` (take that to the idea of recording who looks at the hints!). The only opposition I can see to changing the parameter name or leaving a comment is that it's not how it's done in the _real_ library code, so the player is getting help they may not necessarily get outside of the game.

I'm happy to make a PR for this if it's okay. I am also trying to get a general feel for how much of this library code we can make edits to, in the name of helping the player.

**Comment by pinheadmz** [comment]
Thanks @satsie you can open a PR to https://github.com/saving-satoshi/bech32js and https://github.com/saving-satoshi/bech32py which are source code repos for the packages we install in the game (https://www.npmjs.com/package/@savingsatoshi/bech32js and https://pypi.org/project/savingsatoshi_bech32py/) 

We could also link directly to the spec: https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki#bech32

**Comment by satsie** [comment]
Thank you @pinheadmz! I opened PRs to the repos you mentioned:

https://github.com/saving-satoshi/bech32js/pull/1
https://github.com/saving-satoshi/bech32py/pull/1

I will make a note to self to take care of linking directly to the bech32 spec.

**Comment by pinheadmz** [comment]
Thanks @satsie i merged and published both of those PRs. Since the version bump is patch level there shouldn't be any need to change anything in the application. Also I think we just link to the source code on master branch anyway
